name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os-name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            os-name: Windows
          - runner: ubuntu-24.04
            os-name: Ubuntu

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y \
            cmake \
            build-essential

      - name: Pre-build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd build
          python pre_build.py --vs 2022

      - name: Pre-build (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cd build
          python3 pre_build.py

      - name: Build Release (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cmake --build build\win\vs2022 --config Release --target radeon_gpu_detective_cli rgd_test --parallel %NUMBER_OF_PROCESSORS%

      - name: Build Release (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cmake --build build/linux/make/release --target radeon_gpu_detective_cli rgd_test --parallel $(nproc)

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: build\win\vs2022\release\rgd_test.exe --rgd samples\sample_crash_dump.rgd

      - name: Run tests (Ubuntu)
        if: runner.os == 'Linux'
        run: build/linux/make/release/rgd_test --rgd samples/sample_crash_dump.rgd
